language: python
sudo: false
python:
    - "3.6"
env:
    - POSTIX_STATIC_ROOT=`pwd`/src/static.dist
install:
    - pip install -U pip wheel setuptools codecov coverage
    - pip install -r src/requirements.txt
    - pip install -r src/requirements-dev.txt
script:
    - cd src
    - black --check .
    - python manage.py check
    - py.test --cov=postix tests/ && codecov
cache:
    directories:
        - $HOME/.cache/pip
