# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 15:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0007_auto_20160207_1550")]

    operations = [
        migrations.AlterField(
            model_name="listconstraintproduct",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_list_constraint",
                to="core.Product",
            ),
        )
    ]
