# Generated by Django 2.1.14 on 2019-12-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_product_is_admission"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashdeskConstraint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                (
                    "allowed_cashdesks",
                    models.ManyToManyField(
                        blank=True, to="core.Cashdesk", verbose_name="Allowed Cashdesks"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        to="core.Product",
                        verbose_name="Affected products",
                        related_name="cashdesk_constraints",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
